### ISSUE TITLE
dirty tooth.deb not found.

### ISSUE THREAD

**Issue by victorfmin66** [ElevenPaths/DirtyTooth-RaspberryPi#2]
Hi,
Seems like the dirtytooth.deb is not in the repository. Are you going to upload it to allow the installation of the dirtyTooth on raspberry pi?

Thank you!

**Comment by toolsprods** [comment]
Hello,
you can find it in the releases section:
https://github.com/ElevenPaths/DirtyTooth-RaspberryPi/releases
